---
# Playbook executed by Argo Workflows step "rollback"
- name: Rollback deployment tasks
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    release: blue

  tasks:
    - name: Rollback traffic to test-app-{{ release }}
      kubernetes.core.k8s:
        state: patched
        kind: Service
        name: test-app
        namespace: test-app
        definition:
          spec:
            selector:
              release: "{{ release }}"
