apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-blue
  labels:
    app: test-app
    release: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
      release: blue
  template:
    metadata:
      labels:
        app: test-app
        release: blue
    spec:
      containers:
      - name: web
        image: nginxdemos/hello:0.3-plain-text
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 5
