apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-argo-admin
  namespace: test-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: test-app
